name: Basic 256 CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
        
    - uses: actions/checkout@v4
        
    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install bison flex qt5-qmake qtbase5-dev libqt5serialport5-dev libqt5texttospeech5-dev qtmultimedia5-dev qttools5-dev-tools
        
    - name: Prepare build
      run: |
        qmake BASIC256.pro -config release
    
    - name: Build
      run: |
        make

    - name: Upload binary
      uses: actions/upload-artifact@v4
      with:
        name: Ubuntu 24.04 binary
        path: 'basic256'

